#!/bin/bash

DISCOVERY_PASSWORD="my-password"
DISCOVERY_USERNAME="my-username"
AUTH_REST_SERVER_PORT=8004
EUREKA_URL="my-eureka-url"
ACTIVE_PROFILE="dev"

IMAGE_NAME="auth_serv"

docker run -d -p ${SERVER_PORT}:${SERVER_PORT} \
  -e DISCOVERY_PASSWORD=${DISCOVERY_PASSWORD} \
  -e DISCOVERY_USERNAME=${DISCOVERY_USERNAME} \
  -e REST_SERVER_PORT=${AUTH_REST_SERVER_PORT} \
  -e EUREKA_URL=${EUREKA_URL} \
  -e ACTIVE_PROFILE=${ACTIVE_PROFILE} \

  ${IMAGE_NAME}